name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1   
  logger: ^2.5.0  
#  permission_handler: ^12.0.0+1
  flutter_bluetooth_serial: ^0.4.0
  async: ^2.12.0  






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
